name: gestionferme
description: Une application de gestion de poules pondeuses d'une ferme.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  flutter_speed_dial: ^3.0.5
  shared_preferences: ^2.0.5
  google_fonts: ^2.1.0
  fl_chart: ^0.36.1
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+3
  path_provider: ^2.0.3
  permission_handler: ^8.1.4+2
  flutter_launcher_icons: ^0.9.1
  flutter_svg: ^0.22.0
  pdf: ^3.4.2
  open_file: ^3.2.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^1.2.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/icon_splash.png
  color_dark: "#2b2b2b"
  image_dark: assets/icons/icon_splash.png
  android: true
  ios: true
  windows: true
  web: false
  fullscreen: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
